name: e-tek_update

on:
  workflow_run:
    workflows: ["md5-CI-build"]
    types:
      - completed
  workflow_dispatch:
    #?
# Push via ssh to git@e.coding.net:e-tek/Taromati2/stable-mirror.git
# The contents of the ssh key can be obtained from secrets.BOT_RSA_PRIVATE and secrets.BOT_RSA_PUBLIC
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
       fetch-depth: 7
    #Write the ssh key to the file
    #And set StrictHostKeyChecking
    - name: set ssh key
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/id_rsa
        touch ~/.ssh/id_rsa.pub
        echo "${{ secrets.BOT_RSA_PRIVATE }}" > ~/.ssh/id_rsa
        echo "${{ secrets.BOT_RSA_PUBLIC }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/id_rsa.pub
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
    - name: git push
      run: |
        git config --global user.email "taromati2@foxmail.com"
        git config --global user.name "Taromati2"
        git remote add e-tek git@e.coding.net:e-tek/Taromati2/stable-mirror.git
        git push e-tek master --force
